services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports: 
      - 27017:${MONGO_PORT}
    logging:
      options:
        max-size: 1g
        max-file: 5
    volumes:
      - ./data-base-hotel:/data/db
    command: ["mongod", "--auth"]

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

  server:
    container_name: server
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 3000:${BACKEND_PORT}
    depends_on:
      - mongo
    command: npm run start:dev

  client:
    container_name: client
    restart: always
    build: 
      context: ./frontend
      dockerfile:  Dockerfile.dev
    volumes: 
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 5173:${FRONTEND_PORT}
    depends_on:
      -  server
    command: npm run dev

volumes:
  data-base: {}