# Use root/example as user/password credentials
#version: "3.9"
services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb-dev
    ports: 
      - ${MONGO_PORT}:27017
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - ./data-base-hotel:/data/db
    logging:
      options:
        max-size: 1g
        max-file: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    command: ["mongod", "--auth"]

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-dev
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb-dev
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

  backend:
    container_name: hotel-backend-dev
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - ${BACKEND_PORT}:3000
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    command: npm run start:dev

  frontend:
    container_name: hotel-frontend-dev
    restart: always
    build: 
      context: ./frontend
      dockerfile:  Dockerfile.dev
    volumes: 
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - ${FRONTEND_PORT}:5173
    command: npm run dev

volumes:
  data-base: {}