# Use root/example as user/password credentials
#version: "3.9"
services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb-dev
    ports: 
      - 27017:${MONGO_PORT}
    logging:
      options:
        max-size: 1g
        max-file: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_HOTELS_WRITE_USER: ${MONGO_HOTELS_WRITE_USER}
      MONGO_HOTELS_WRITE_PASSWORD: ${MONGO_HOTELS_WRITE_PASSWORD}
      MONGO_HOTELS_READ_USER: ${MONGO_HOTELS_READ_USER}
      MONGO_HOTELS_READ_PASSWORD: ${MONGO_HOTELS_READ_PASSWORD}
      MONGO_USERS_WRITE_USER: ${MONGO_USERS_WRITE_USER}
      MONGO_USERS_WRITE_PASSWORD: ${MONGO_USERS_WRITE_PASSWORD}
      MONGO_USERS_READ_USER: ${MONGO_USERS_READ_USER}
      MONGO_USERS_READ_PASSWORD: ${MONGO_USERS_READ_PASSWORD}
    volumes:
      # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data-base-hotel:/data/db
    command: ["mongod", "--auth"]

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-dev
    restart: always
    ports:
      - 8081:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb-dev
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

  backend:
    container_name: hotel-backend-dev
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 3000:${BACKEND_PORT}
    environment:
      MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:${MONGO_PORT}/admin?authSource=admin
    depends_on:
      - mongo
    command: npm run start:dev

  frontend:
    container_name: hotel-frontend-dev
    restart: always
    build: 
      context: ./frontend
      dockerfile:  Dockerfile.dev
    volumes: 
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 5173:${FRONTEND_PORT}
    depends_on:
      -  backend
    command: npm run dev

volumes:
  data-base: {}